name: sebastian
description: League of legends assistant app.
publish_to: "none"
version: 3.7.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DI
  get_it: 7.6.4

  # Data
  http: 1.1.0
  json_annotation: 4.8.1

  # Presentation
  bloc: 8.1.2
  flutter_bloc: 8.1.3

  # UI
  data_table_2: 2.5.9

  # Extensions
  rxdart: 0.27.7

  # Utils
  equatable: 2.0.5
  intl: any #Resolved by flutter_localizations
  path: any #Resolved by Flutter
  meta: any #Resolved by Flutter
  collection: any #Resolved by Flutter

  # Plugins
  shared_preferences: 2.2.2
  file_picker: 6.1.1
  package_info_plus: 4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: 3.0.1

  # Codegen
  build_runner: 2.4.6
  json_serializable: 6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
