name: sebastian
description: League of legends assistant app.
publish_to: "none"
version: 3.2.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DI
  get_it: 7.2.0

  # Data
  http: 0.13.5
  json_annotation: 4.7.0

  # Presentation
  bloc: 8.1.0
  flutter_bloc: 8.1.1

  # UI
  data_table_2: 2.3.8

  # Extensions
  rxdart: 0.27.7

  # Utils
  equatable: 2.0.5
  intl: #Resolved by flutter_localizations
  path: #Resolved by Flutter
  meta: #Resolved by Flutter
  collection: #Resolved by Flutter

  # Plugins
  shared_preferences: 2.0.15
  file_picker: 5.2.3
  package_info_plus: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: 2.0.1

  # Codegen
  build_runner: 2.3.2
  json_serializable: 6.5.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
