name: sebastian
description: League of legends assistant app.
publish_to: "none"
version: 4.2.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DI
  get_it: 7.7.0

  # Data
  http: 1.2.1
  json_annotation: 4.9.0

  # Presentation
  bloc: 8.1.4
  flutter_bloc: 8.1.5

  # UI
  data_table_2: 2.5.12

  # Extensions
  rxdart: 0.27.7

  # Utils
  equatable: 2.0.5
  intl: any #Resolved by flutter_localizations
  path: any #Resolved by Flutter
  meta: any #Resolved by Flutter
  collection: any #Resolved by Flutter

  # Plugins
  shared_preferences: 2.2.3
  file_picker: 8.0.3
  package_info_plus: 8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: 4.0.0

  # Codegen
  build_runner: 2.4.9
  json_serializable: 6.8.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/