name: sebastian
description: League of legends assistant app.
publish_to: "none"
version: 3.6.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DI
  get_it: 7.2.0

  # Data
  http: 0.13.5
  json_annotation: 4.8.0

  # Presentation
  bloc: 8.1.1
  flutter_bloc: 8.1.2

  # UI
  data_table_2: 2.4.1

  # Extensions
  rxdart: 0.27.7

  # Utils
  equatable: 2.0.5
  intl: any #Resolved by flutter_localizations
  path: any #Resolved by Flutter
  meta: any #Resolved by Flutter
  collection: any #Resolved by Flutter

  # Plugins
  shared_preferences: 2.0.20
  file_picker: 5.2.6
  package_info_plus: 3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: 2.0.1

  # Codegen
  build_runner: 2.3.2
  json_serializable: 6.6.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
