name: champmastery
description: A new Flutter project.
publish_to: "none"
version: 2.3.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1

  rxdart: ^0.27.3
  get_it: ^7.2.0

  #UI
  data_table_2: ^2.3.5

  #Utils
  path: ^1.8.1
  intl: ^0.17.0
  meta: ^1.7.0
  equatable: ^2.0.3

  #Plugins
  shared_preferences: ^2.0.15
  file_picker: ^5.0.0
  package_info_plus: ^1.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/champions_ru.json
    - assets/images/
