name: sebastian
description: League of legends assistant app.
publish_to: "none"
version: 3.7.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # DI
  get_it: 7.6.0

  # Data
  http: 0.13.6
  json_annotation: 4.8.1

  # Presentation
  bloc: 8.1.1
  flutter_bloc: 8.1.2

  # UI
  data_table_2: 2.5.0

  # Extensions
  rxdart: 0.27.7

  # Utils
  equatable: 2.0.5
  intl: any #Resolved by flutter_localizations
  path: any #Resolved by Flutter
  meta: any #Resolved by Flutter
  collection: any #Resolved by Flutter

  # Plugins
  shared_preferences: 2.1.1
  file_picker: 5.3.0
  package_info_plus: 4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints
  flutter_lints: 2.0.1

  # Codegen
  build_runner: 2.4.4
  json_serializable: 6.6.2

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
